### PR TITLE
fix(openwhisk): convert base64 encoded json request bodies into strings

### LINKED ISSUE #141: OpenWhisk: JSON request body is base64 encoded
Trying to get https://github.com/adobe/helix-publish/pull/771 to work, I'm noticing parsing errors for the JSON request body, which arrives as `eyJpbmRleGNvbmZpZyI6eyJpbmRpY2VzIj...` i.e. base64 encoded.

According to: https://medium.com/openwhisk/whats-new-web-actions-e0ffeef1bea3

> It is also possible to access the “raw” HTTP query string and body entity. This means web actions can receive content-types other than JSON objects. A raw web action receives the request query parameters and body via two properties of the input argument: `__ow_query` and `__ow_body`. The former is a string as in `__ow_query = "msg=Hello&name=Reader"`, and the latter is either a plain string, **or a base64 encoded string when the content-type representation is binary data**. An example of a raw web action that receives **a JSON object (which is considered a binary data type)** as __ow_body and converts it to String follows:

JSON is a binary format!

### PR DESCRIPTION
**Pull request by trieloff**
fixes #141

### CODE REVIEW

File: src/template/index.js [hunk 1]
```diff
@@ -139,7 +139,13 @@ async function openwhisk(params = {}) {
 
     let body;
     if (!/^(GET|HEAD)$/i.test(method)) {
-      body = isBinary(headers['content-type']) ? Buffer.from(rawBody, 'base64') : rawBody;
+      body = isBinary(headers['content-type'])
+        ? Buffer.from(rawBody, 'base64')
+        : rawBody;
+      // binaries and JSON (!) are base64 encoded
+      if (/application\/json/.test(headers['content-type'])) {
+        body = Buffer.from(rawBody, 'base64').toString();
```
Comment (tripodsan) [inline src/template/index.js:147]:
```suggestion
        body = Buffer.from(rawBody, 'base64');
```

Comment (tripodsan) [inline src/template/index.js:147]:
```suggestion
        body = Buffer.from(rawBody, 'base64').toString('utf-8');
```

**Review by tripodsan — APPROVED** [review]

**Review by stefan-guggisberg — APPROVED** [review]
