### PR TITLE
Various fixes

### LINKED ISSUE #74: improve isBinary computation for openwhisk
e.g. the current `isBinary('text/yaml')` returns `false` but should be `true`.
only the media types listed here as non binary should return `false`:
https://doc.akka.io/api/akka-http/10.1.11/akka/http/scaladsl/model/MediaTypes$.html

see https://github.com/adobe/helix-static/issues/464

### PR DESCRIPTION
**Pull request by tripodsan**
- fixes #74 
- disable route generation by default see #45

### CODE REVIEW

File: src/deploy/BaseDeployer.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ class BaseDeployer {
         return;
       }
       this.log.info(`id: ${chalk.grey(id)}`);
-      if (ret.status === 404 && retry404) {
+      if ((ret.status === 404 || ret.status === 500) && retry404) {
```
Comment (tripodsan) [inline src/deploy/BaseDeployer.js:100]: when omitting the route creation, deploying the action is sometimes too quick and the first requests results in a 500... so we consider the retries also for 500.

**Review by trieloff — APPROVED** [review]
