### PR TITLE
fix: update links should link route to alias, not specific version

### LINKED ISSUE #399: Make integration for `v{N}` go to function alias `v{N}`
Right now, when a new function symbolic `X.Y.Z` is created, an API Gateway integration is installed that routes the external address `/helix-services/function/vX` to function `helix-services--function:X_Y_Z`. Instead, it could route to function alias `helix-services--function:vX`, which would make a lot of integration installations obsolete.

/cc: @tripodsan

### PR DESCRIPTION
**Pull request by dominique-pfister**
fix #399

### CODE REVIEW

File: src/deploy/AWSDeployer.js [hunk 1]
```diff
@@ -654,81 +657,105 @@ export default class AWSDeployer extends BaseDeployer {
...
       this.log.info(chalk`--: fetching alias ...`);
       res = await this._lambda.send(new GetAliasCommand({
         FunctionName: functionName,
         Name: functionVersion,
       }));
-      aliasArn = res.AliasArn;
       incrementalVersion = res.FunctionVersion;
-      this.log.info(chalk`{green ok}: ${aliasArn}`);
+      // eslint-disable-next-line prefer-destructuring
+      this._accountId = res.AliasArn.split(':')[4];
```
Comment (dominique-pfister) [inline src/deploy/AWSDeployer.js:670]: extract the account id from the alias retrieved

File: test/aws.integration.js [hunk 2]
```diff
@@ -71,14 +71,35 @@ describe('AWS Integration Test', () => {
...
+    const builder = new CLI()
+      .prepare([
+        '--no-build',
+        '--no-hints',
+        '--verbose',
+        '--target', 'aws',
+        '-l', 'major', '-l', 'minor',
+        '--aws-region', 'us-east-1',
+        '--aws-api', 'lqmig3v5eb',
+        '--aws-role', 'arn:aws:iam::118435662149:role/service-role/helix-service-role-ogu32wiz',
```
Comment (dominique-pfister) [inline test/aws.integration.js:84]: corresponds to our common `npm run deploy-sequences`

File: test/aws.integration.js [hunk 3]
```diff
@@ -71,14 +71,51 @@ describe('AWS Integration Test', () => {
...
+      ]);
+    builder.cfg._logger = new TestLogger();
+
+    await builder.run();
+
+    let ret;
+    for (let tries = 3; tries >= 0; tries -= 1) {
+      // eslint-disable-next-line no-await-in-loop
+      ret = await fetch('https://lqmig3v5eb.execute-api.us-east-1.amazonaws.com/simple-package/simple-name/v1/foo');
+      if (ret.status !== 200) {
```
Comment (dominique-pfister) [inline test/aws.integration.js:94]: verify the v1 route doesn't return a 500 🙄

**Review by tripodsan — APPROVED** [review]
