### PR TITLE
fix: add tags to newly created polyfunc bucket

### LINKED ISSUE #243: AWS: allow to specify template bucket for lambda deployments
some accounts require buckets to comply to special tags or permissions. it would be convenient to specify
a template bucket where tags and public access policies could be copied from when creating the deployment buckets.

### PR DESCRIPTION
**Pull request by dominique-pfister**
fix #243

Uses template bucket `helix-deploy-template` by default, logs a warning if not found but continues working.

### CODE REVIEW

File: src/deploy/AWSConfig.js [hunk 1]
```diff
@@ -27,6 +27,7 @@ export default class AWSConfig {
       createAuthorizer: '',
       attachAuthorizer: '',
       identitySources: ['$request.header.Authorization'],
+      deployTemplate: 'helix-deploy-template',
```
Comment (dominique-pfister) [inline src/deploy/AWSConfig.js:30]: default template bucket name

File: src/deploy/AWSDeployer.js [hunk 2]
```diff
@@ -151,6 +152,44 @@ export default class AWSDeployer extends BaseDeployer {
       Bucket: this._bucket,
     }));
     this.log.info(chalk`{green ok:} bucket ${data.Location} created`);
+
+    const { deployTemplate } = this._cfg;
+    if (!deployTemplate) {
+      return;
+    }
```
Comment (dominique-pfister) [inline src/deploy/AWSDeployer.js:159]: If there's no deploy template bucket name, stop

**Review by tripodsan — APPROVED** [review]
